name: Dev

on:
  push:
    branches: [dev, refactor]  # TODO: убрать refactor после завершения рефакторинга

jobs:
  matrix:
    uses: ./.github/workflows/_build-matrix.yml
    with:
      build_type: Debug
