name: Linux

on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: 'dev'
             
        - name: Setup Environment
          run: | 
            sudo apt-get update -qq
            sudo apt-get install gcc-multilib
            sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev
        - name: Build Library
          run: |
            ls  -a /home/runner/work/temporary/temporary/third-party/FrPr/fwk 
            tree .
            cmake -H. -B_build -DRAYLIB_LIBTYPE=STATIC -DPLATFORM=Desktop
            cmake --build _build
        