name: Build MSVC Profile (Manual)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build configuration'
        required: true
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release

jobs:
  windows-msvc-profile:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - run: ./build.bat msvc ${{ inputs.build_type }} static profile

      - uses: actions/upload-artifact@v4
        with:
          name: windows-msvc-profile-${{ inputs.build_type }}
          path: |
            _build/msvc-${{ inputs.build_type }}/app/${{ inputs.build_type }}/app.exe
            _build/msvc-${{ inputs.build_type }}/app/${{ inputs.build_type }}/app.pdb
            _build/msvc-${{ inputs.build_type }}/app/${{ inputs.build_type }}/assets/
          retention-days: 1