name: Windows

on: 
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_windows:
    runs-on: windows-latest
    steps:  
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: 'dev'

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v2

        - name: Build Library (MinGW-w64 32bit)
          run: |
          
            x86_64-w64-mingw32-gcc.exe --version
            windres.exe --version
            dir C:\msys64\mingw64\bin
            cmake . -B_build -DRAYLIB_LIBTYPE=STATIC -DPLATFORM=Desktop -DIS_STATIC=ON -DCMAKE_CXX_FLAGS="/MT" -DCMAKE_C_FLAGS="/MT" -DBUILD_SHARED_LIBS=OFF
            cmake --build _build --config Release
            mkdir _artifacts
            Copy-Item -Path "_build/Release/app.exe" -Destination "_artifacts/"

        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: files
            path: ./_artifacts/app.exe
            retention-days: 1